name: MobiDL-ONT-VariantCalling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - clair3==1.0.4 
  - cromwell==83
  - sambamba==1.0
  - minimap2==2.26
  - gatk4==4.4.0.0
  - bcftools==1.18
  - tabix==1.11
  - seqkit==2.5.1
  - samtools==1.18
