{
	"ONT_VariantCalling.fastqPath": "String",
	"ONT_VariantCalling.refFa": "File",
	"ONT_VariantCalling.refFai": "File",
	"ONT_VariantCalling.modelPath": "String",
	"ONT_VariantCalling.outputPath": "String",

	"ONT_VariantCalling.extFq" = "*.fastq",
	"ONT_VariantCalling.maxDepth" = 1,
	"ONT_VariantCalling.gzip" = false,
	"ONT_VariantCalling.qual": 748,
	"ONT_VariantCalling.bedRegions": "File? (optional)",
	"ONT_VariantCalling.name": "String? (optional)",

	"ONT_VariantCalling.BED2ARRAY.memoryByThreads": 768,
	"ONT_VariantCalling.BED2ARRAY.threads": 1,
	"ONT_VariantCalling.CALLVARBAM.path_exe": "clair.py",
	"ONT_VariantCalling.CALLVARBAM.activation_only": false,
	"ONT_VariantCalling.CALLVARBAM.dcov": 250,
	"ONT_VariantCalling.CALLVARBAM.debug": false,
	"ONT_VariantCalling.CALLVARBAM.fastPlotting": false,
	"ONT_VariantCalling.CALLVARBAM.haploidPrecision": false,
	"ONT_VariantCalling.CALLVARBAM.haploidSensitive": false,
	"ONT_VariantCalling.CALLVARBAM.maxPlot": 10,
	"ONT_VariantCalling.CALLVARBAM.minCoverage": 4,
	"ONT_VariantCalling.CALLVARBAM.outputForEnsemble": false,
	"ONT_VariantCalling.CALLVARBAM.parallelLevel": 2,
	"ONT_VariantCalling.CALLVARBAM.pypy": "pypy",
	"ONT_VariantCalling.CALLVARBAM.pysamForAllIndelBases": false,
	"ONT_VariantCalling.CALLVARBAM.samtools": "samtools",
	"ONT_VariantCalling.CALLVARBAM.stopConsiderLeftEdge": false,
	"ONT_VariantCalling.CALLVARBAM.subString": "(.bam)",
	"ONT_VariantCalling.CALLVARBAM.subStringReplace": "",
	"ONT_VariantCalling.CALLVARBAM.threshold": 0.125,
	"ONT_VariantCalling.CALLVARBAM.workers": 8,
	"ONT_VariantCalling.CALLVARBAM.threads": 1,
	"ONT_VariantCalling.CALLVARBAM.memoryByThreads": 768,
	"ONT_VariantCalling.CONCATENATEFILES.subString": "^[0-9]+-",
	"ONT_VariantCalling.CONCATENATEFILES.threads": 1,
	"ONT_VariantCalling.CONCATENATEFILES.memoryByThreads": 768,
	"ONT_VariantCalling.FAI2BED.subString": ".?(fa)?(sta)?.fai$",
	"ONT_VariantCalling.FAI2BED.subStringReplace": ".bed",
	"ONT_VariantCalling.FAI2BED.threads": 1,
	"ONT_VariantCalling.FAI2BED.memoryByThreads": 768,
	"ONT_VariantCalling.FINDFILES.threads": 1,
	"ONT_VariantCalling.FINDFILES.memoryByThreads": 768,
	"ONT_VariantCalling.GATHERVCFFILES.path_exe": "gatk",
	"ONT_VariantCalling.GATHERVCFFILES.subStringReplace": ".gather",
	"ONT_VariantCalling.GATHERVCFFILES.reorder": true,
	"ONT_VariantCalling.GATHERVCFFILES.threads": 1,
	"ONT_VariantCalling.GATHERVCFFILES.memoryByThreads": 768,
	"ONT_VariantCalling.INDEX.path_exe": "sambamba",
	"ONT_VariantCalling.INDEX.checkBins": false,
	"ONT_VariantCalling.INDEX.threads": 1,
	"ONT_VariantCalling.INDEX.memoryByThreads": 768,
	"ONT_VariantCalling.MAPONT.path_exe": "minimap2",
	"ONT_VariantCalling.MAPONT.path_exe_samtools": "samtools",
	"ONT_VariantCalling.MAPONT.CIGAROperator": false,
	"ONT_VariantCalling.MAPONT.KmerSize": 15,
	"ONT_VariantCalling.MAPONT.MDtag": false,
	"ONT_VariantCalling.MAPONT.SAMoutput": true,
	"ONT_VariantCalling.MAPONT.ZDropScore1": 400,
	"ONT_VariantCalling.MAPONT.ZDropScore2": 200,
	"ONT_VariantCalling.MAPONT.filterOutFracMin": 2.0E-4,
	"ONT_VariantCalling.MAPONT.finGTAG": "n",
	"ONT_VariantCalling.MAPONT.gapExtension1": 2,
	"ONT_VariantCalling.MAPONT.gapExtension2": 1,
	"ONT_VariantCalling.MAPONT.gapPenalty1": 4,
	"ONT_VariantCalling.MAPONT.gapPenalty2": 24,
	"ONT_VariantCalling.MAPONT.homopolymerCompressed": false,
	"ONT_VariantCalling.MAPONT.matchingScore": 2,
	"ONT_VariantCalling.MAPONT.maxIntronLen": 200000,
	"ONT_VariantCalling.MAPONT.minChainScore": 40,
	"ONT_VariantCalling.MAPONT.minMinimizerChain": 3,
	"ONT_VariantCalling.MAPONT.minPeakDP": 80,
	"ONT_VariantCalling.MAPONT.minSec2Prim": 0.8,
	"ONT_VariantCalling.MAPONT.minWindowSize": 10,
	"ONT_VariantCalling.MAPONT.miniBatch": 500000000,
	"ONT_VariantCalling.MAPONT.mismatchPenalty": 4,
	"ONT_VariantCalling.MAPONT.platformReads": "ONT",
	"ONT_VariantCalling.MAPONT.retainSec": 5,
	"ONT_VariantCalling.MAPONT.splitIndex": "4G",
	"ONT_VariantCalling.MAPONT.stopChain": 5000,
	"ONT_VariantCalling.MAPONT.subString": ".(fastq|fq)(.gz)?",
	"ONT_VariantCalling.MAPONT.subStringReplace": "",
	"ONT_VariantCalling.MAPONT.useSoftClipping": false,
	"ONT_VariantCalling.MAPONT.writeCIGARSup65535": false,
	"ONT_VariantCalling.MAPONT.threads": 1,
	"ONT_VariantCalling.MAPONT.memoryByThreads": 768,

	"ONT_VariantCalling.CALLVARBAM.bedRegions": "File? (optional)",
	"ONT_VariantCalling.CALLVARBAM.candidateVcf": "File? (optional)",
	"ONT_VariantCalling.CALLVARBAM.logPath": "String? (optional)",
	"ONT_VariantCalling.FAI2BED.name": "String? (optional)",
	"ONT_VariantCalling.FAI2BED.outputPath": "String? (optional)",
	"ONT_VariantCalling.FINDFILES.executable": "Boolean? (optional)",
	"ONT_VariantCalling.FINDFILES.gid": "Int? (optional)",
	"ONT_VariantCalling.FINDFILES.minDepth": "Int? (optional)",
	"ONT_VariantCalling.FINDFILES.readable": "Boolean? (optional)",
	"ONT_VariantCalling.FINDFILES.regexpPath": "String? (optional)",
	"ONT_VariantCalling.FINDFILES.uid": "Int? (optional)",
	"ONT_VariantCalling.FINDFILES.writable": "Boolean? (optional)",
	"ONT_VariantCalling.GATHERVCFFILES.name": "String? (optional)",
	"ONT_VariantCalling.INDEX.sample": "String? (optional)",
	"ONT_VariantCalling.MAPONT.csShort": "Boolean? (optional)",
	"ONT_VariantCalling.MAPONT.dumpIndexFile": "File? (optional)"
}
